name: books
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - seaborn
  - matplotlib
  - jupyterlab
  - jupyterlab-git
  - requests
  - requests-cache
  - pillow
  - beautifulsoup4
  - python-dotenv